### ISSUE TITLE
unable build on python 3.6

### ISSUE THREAD

**Issue by mimi1vx** [bitprophet/pytest-relaxed#1] opened 2017-11-15 18:53 UTC
```
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
[    4s] Traceback (most recent call last):
[    4s]   File "setup.py", line 22, in <module>
[    4s]     long_description="\n" + open('README.rst').read(),
[    4s]   File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
[    4s]     return codecs.ascii_decode(input, self.errors)[0]
[    4s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1089: ordinal not in range(128)
```
[    4s] error: Bad exit status from /var/tmp/rpm-tmp.D2pzNW (%build)

**Comment by bitprophet** [comment] 2018-03-28 19:47
Weird, I can't reproduce this on my end, or on Travis :( using a pyenv-built python 3 on macOS here, and Travis is Debian or Ubuntu based I believe. If you're still having this issue & can get more details about your local system, do comment, otherwise closing as can't-reproduce.

**Closed by bitprophet** 2018-03-28 19:47 UTC

**Comment by mimi1vx** [comment] 2018-03-29 13:05
I think bug is clear . nonascii character in `README.rst` file. 

proper way  to load text file into setup.py will be:

```
from io import open

long_description=open('README.rst', encoding='utf-8').read(),
```
